name: opttrajflutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: 1.5.0
  provider: ^6.0.5
  flutter_map: ^6.1.0 # Add this
  latlong2: ^0.9.0 # Add this
  flutter_polyline_points: ^2.0.0 # Keep this

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true